--- #YAML:1.0
name:               HTML-CalendarMonth
version:            1.23
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor:     0
    DateTime::Locale:    0.45
    File::Spec:          0
    HTML::ElementTable:  1.18
    Time::Local:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
